# Generated by Django 4.2.16 on 2024-11-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecetarioBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetarios.bebida')),
                ('recetario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetarios.recetario')),
            ],
            options={
                'unique_together': {('recetario', 'bebida')},
            },
        ),
        migrations.AddField(
            model_name='bebida',
            name='categorias',
            field=models.ManyToManyField(related_name='bebidas', to='recetarios.categoria'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetarios.dimension'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='ingredientes',
            field=models.ManyToManyField(related_name='bebidas', to='recetarios.ingrediente'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='recetarios',
            field=models.ManyToManyField(through='recetarios.RecetarioBebida', to='recetarios.recetario'),
        ),
    ]
