# Generated by Django 4.2.16 on 2024-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetarios', '0002_bebida_descripcion_bebida_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='recetarios',
        ),
        migrations.AddField(
            model_name='recetario',
            name='bebidas',
            field=models.ManyToManyField(related_name='recetarios', to='recetarios.bebida'),
        ),
    ]
