# Generated by Django 4.2.16 on 2024-11-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetario',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='recetario',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recetario',
            name='recetas',
        ),
    ]
