# Generated by Django 4.2.16 on 2024-11-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_rename_description_recetario_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='Recetario',
        ),
    ]
